# Generated by Django 5.2.15 on 2026-06-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(default='hero/default.jpg', upload_to='hero/')),
                ('button_link', models.CharField(default='/packages', max_length=200)),
            ],
        ),
    ]
