# Generated by Django 5.2.15 on 2026-06-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('bronze', 'Bronze')], max_length=10, unique=True)),
                ('price', models.CharField(max_length=50)),
                ('color', models.CharField(default='bg-gradient-to-r from-gray-300 to-yellow-400', max_length=100)),
                ('features', models.JSONField(default=list)),
            ],
        ),
    ]
