# Generated by Django 5.2.15 on 2026-06-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
