# Generated by Django 5.2.15 on 2026-06-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='hero_videos/')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
