# Generated by Django 5.2.15 on 2026-06-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_herovideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='herovideo',
            name='video_url',
            field=models.URLField(blank=True, help_text='Paste Cloudinary or external video URL', null=True),
        ),
        migrations.AlterField(
            model_name='herovideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='hero_videos/'),
        ),
    ]
