# Generated by Django 5.2.15 on 2026-06-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_herovideo_video_url_alter_herovideo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='tier',
            field=models.CharField(choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('silver', 'Silver'), ('custom', 'Custom')], max_length=10, unique=True),
        ),
    ]
